version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: carconnect
      MYSQL_USER: alex
      MYSQL_PASSWORD: P@ssw0rd
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - webnet

  php-app:
    build: .
    container_name: php-app
    depends_on:
      - db
    networks:
      - webnet
    ports:
      - "8000:80"
    restart: always

  nginx:
    build: .
    container_name: nginx-proxy
    depends_on:
      - php-app
    networks:
      - webnet
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  mysql_data:

networks:
  webnet:
